# Generated by Django 2.0.7 on 2019-09-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='Description',
            new_name='description',
        ),
    ]
