# Generated by Django 2.0.7 on 2019-09-19 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('music_app', '0002_auto_20190918_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='login_app.Users'),
            preserve_default=False,
        ),
    ]
