# Generated by Django 2.0.7 on 2019-09-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_auto_20190919_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='document',
            new_name='file',
        ),
        migrations.AddField(
            model_name='song',
            name='document_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
