# Generated by Django 2.0.7 on 2019-09-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0006_auto_20190919_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='document_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='file',
        ),
        migrations.AddField(
            model_name='song',
            name='document',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
