# Generated by Django 2.0.7 on 2019-09-19 18:26

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('music_app', '0007_auto_20190919_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=builtins.max)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music_app.Playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='login_app.Users')),
            ],
        ),
    ]
