# Generated by Django 2.0.7 on 2019-09-23 11:08

import constrainedfilefield.fields.file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0009_auto_20190919_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='document',
            field=constrainedfilefield.fields.file.ConstrainedFileField(blank=True, content_types=['image/png'], max_upload_size=10240, mime_lookup_length=4096, null=True, upload_to='documents'),
        ),
    ]
