# Generated by Django 2.0.7 on 2019-09-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0010_auto_20190923_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
